import 'dart:typed_data';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:invoicehub/models/profile.dart';
import 'package:invoicehub/models/business_models.dart';
import 'package:invoicehub/models/khata_model.dart';
import 'package:invoicehub/repositories/khata_repository.dart';

class KhataPdfService {
  static final PdfColor _brandPrimary = PdfColor.fromHex('#3D5AFE');
  static final PdfColor _brandSecondary = PdfColor.fromHex('#00BFA6');
  static final PdfColor _gaveRed = PdfColor.fromHex('#E53935');
  static final PdfColor _gotGreen = PdfColor.fromHex('#43A047');
  static final PdfColor _greyLight = PdfColor.fromHex('#F5F5F5');
  static final PdfColor _greyDark = PdfColor.fromHex('#424242');

  /// Generate CA-Style Individual Customer Ledger PDF
  static Future<Uint8List> generateCustomerLedgerPdf({
    required Profile shop,
    required Customer customer,
    required List<KhataTransaction> transactions,
    String? dateRangeText,
    PdfPageFormat format = PdfPageFormat.a4,
  }) async {
    final fontBase = await PdfGoogleFonts.notoSansRegular();
    final fontBold = await PdfGoogleFonts.notoSansBold();

    final pdf = pw.Document(
      theme: pw.ThemeData.withFont(
        base: fontBase,
        bold: fontBold,
      ),
    );

    // Calculate Totals
    double totalGave = 0.0;
    double totalGot = 0.0;
    for (final tx in transactions) {
      if (tx.isGave) {
        totalGave += tx.amount;
      } else {
        totalGot += tx.amount;
      }
    }
    final netBalance = totalGave - totalGot;

    // Chronological transactions for table running balance
    final chronoTxs = List<KhataTransaction>.from(transactions)
      ..sort((a, b) => a.transactionDate.compareTo(b.transactionDate));

    final shopNameStr = shop.shopName ?? 'My Shop';

    pdf.addPage(
      pw.MultiPage(
        pageFormat: format,
        margin: const pw.EdgeInsets.fromLTRB(28, 24, 28, 24),
        header: (context) => context.pageNumber == 1
            ? pw.SizedBox.shrink()
            : pw.Padding(
                padding: const pw.EdgeInsets.only(bottom: 8),
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(
                      'Khata Statement - ${customer.customerName}',
                      style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
                    ),
                    pw.Text(
                      'Shop: $shopNameStr',
                      style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
                    ),
                  ],
                ),
              ),
        footer: (context) => pw.Padding(
          padding: const pw.EdgeInsets.only(top: 8),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text('Generated by InvoiceHub - Khata Book Module', style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
              pw.Text(
                'Page ${context.pageNumber} of ${context.pagesCount}',
                style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
              ),
            ],
          ),
        ),
        build: (pw.Context context) {
          return [
            _buildHeader(shop, 'CUSTOMER ACCOUNT LEDGER STATEMENT'),
            pw.SizedBox(height: 14),
            _buildCustomerAndDateSection(shop, customer, dateRangeText),
            pw.SizedBox(height: 14),
            _buildFinancialSummaryCards(totalGave, totalGot, netBalance),
            pw.SizedBox(height: 16),
            _buildTransactionLedgerTable(chronoTxs),
            pw.Spacer(),
            _buildSignatureBlock(shop),
          ];
        },
      ),
    );

    return pdf.save();
  }

  /// Generate CA-Style Shop-wide Financial Khata Summary PDF
  static Future<Uint8List> generateShopKhataReportPdf({
    required Profile shop,
    required List<CustomerKhataSummary> customerSummaries,
    String? dateRangeText,
    PdfPageFormat format = PdfPageFormat.a4,
  }) async {
    final fontBase = await PdfGoogleFonts.notoSansRegular();
    final fontBold = await PdfGoogleFonts.notoSansBold();

    final pdf = pw.Document(
      theme: pw.ThemeData.withFont(
        base: fontBase,
        bold: fontBold,
      ),
    );

    double totalReceivables = 0.0;
    double totalPayables = 0.0;
    double overallGave = 0.0;
    double overallGot = 0.0;

    for (final s in customerSummaries) {
      overallGave += s.totalGave;
      overallGot += s.totalGot;
      if (s.netBalance > 0) {
        totalReceivables += s.netBalance;
      } else if (s.netBalance < 0) {
        totalPayables += s.netBalance.abs();
      }
    }

    final shopNameStr = shop.shopName ?? 'My Shop';

    pdf.addPage(
      pw.MultiPage(
        pageFormat: format,
        margin: const pw.EdgeInsets.fromLTRB(28, 24, 28, 24),
        header: (context) => context.pageNumber == 1
            ? pw.SizedBox.shrink()
            : pw.Padding(
                padding: const pw.EdgeInsets.only(bottom: 8),
                child: pw.Text(
                  'Shop Khata Financial Summary - $shopNameStr',
                  style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
                ),
              ),
        footer: (context) => pw.Padding(
          padding: const pw.EdgeInsets.only(top: 8),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text('Generated by InvoiceHub - Accounting Report', style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
              pw.Text(
                'Page ${context.pageNumber} of ${context.pagesCount}',
                style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
              ),
            ],
          ),
        ),
        build: (pw.Context context) {
          return [
            _buildHeader(shop, 'SHOP KHATA FINANCIAL SUMMARY (CA REPORT)'),
            pw.SizedBox(height: 14),
            _buildShopReportMeta(shop, dateRangeText, customerSummaries.length),
            pw.SizedBox(height: 14),
            _buildShopSummaryCards(totalReceivables, totalPayables, overallGave, overallGot),
            pw.SizedBox(height: 16),
            _buildCustomerSummariesTable(customerSummaries),
            pw.Spacer(),
            _buildSignatureBlock(shop),
          ];
        },
      ),
    );

    return pdf.save();
  }

  static pw.Widget _buildHeader(Profile shop, String reportTitle) {
    final shopNameStr = shop.shopName ?? 'My Shop';
    final addressStr = shop.address ?? '';
    final mobileStr = shop.mobile ?? '';

    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      decoration: pw.BoxDecoration(
        borderRadius: pw.BorderRadius.circular(6),
        gradient: pw.LinearGradient(
          colors: [_brandPrimary, _brandSecondary],
          begin: pw.Alignment.topLeft,
          end: pw.Alignment.bottomRight,
        ),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Center(
            child: pw.Text(
              '|| Jay Swaminarayan ||',
              style: pw.TextStyle(
                fontSize: 9,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.white,
              ),
            ),
          ),
          pw.SizedBox(height: 4),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    shopNameStr,
                    style: pw.TextStyle(
                      fontSize: 18,
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColors.white,
                    ),
                  ),
                  if (addressStr.isNotEmpty)
                    pw.Text(
                      addressStr,
                      style: const pw.TextStyle(fontSize: 9, color: PdfColors.white),
                    ),
                  if (mobileStr.isNotEmpty)
                    pw.Text(
                      'Phone: $mobileStr',
                      style: const pw.TextStyle(fontSize: 9, color: PdfColors.white),
                    ),
                ],
              ),
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.end,
                children: [
                  pw.Text(
                    reportTitle,
                    style: pw.TextStyle(
                      fontSize: 11,
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColors.white,
                    ),
                  ),
                  pw.Text(
                    'Date: ${DateFormat('dd MMM yyyy').format(DateTime.now())}',
                    style: const pw.TextStyle(fontSize: 8, color: PdfColors.white),
                  ),
                ],
              ),
            ],
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildCustomerAndDateSection(Profile shop, Customer customer, String? dateRangeText) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        color: _greyLight,
        borderRadius: pw.BorderRadius.circular(4),
        border: pw.Border.all(color: PdfColors.grey300),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text('STATEMENT FOR:', style: pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold, color: _greyDark)),
              pw.Text(customer.customerName, style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
              if (customer.mobile != null && customer.mobile!.isNotEmpty)
                pw.Text('Mobile: ${customer.mobile}', style: const pw.TextStyle(fontSize: 9)),
              if (customer.address != null && customer.address!.isNotEmpty)
                pw.Text('Address: ${customer.address}', style: const pw.TextStyle(fontSize: 9)),
            ],
          ),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Text('PERIOD / DURATION:', style: pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold, color: _greyDark)),
              pw.Text(dateRangeText ?? 'All Time', style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, color: _brandPrimary)),
              if (customer.gstNumber != null && customer.gstNumber!.isNotEmpty)
                pw.Text('GSTIN: ${customer.gstNumber}', style: const pw.TextStyle(fontSize: 9)),
            ],
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildShopReportMeta(Profile shop, String? dateRangeText, int totalCustomers) {
    final shopNameStr = shop.shopName ?? 'My Shop';

    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        color: _greyLight,
        borderRadius: pw.BorderRadius.circular(4),
        border: pw.Border.all(color: PdfColors.grey300),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text('BUSINESS / SHOP:', style: pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold, color: _greyDark)),
              pw.Text(shopNameStr, style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
              pw.Text('Total Active Customers: $totalCustomers', style: const pw.TextStyle(fontSize: 9)),
            ],
          ),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Text('REPORT PERIOD:', style: pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold, color: _greyDark)),
              pw.Text(dateRangeText ?? 'All Time', style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, color: _brandPrimary)),
            ],
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildFinancialSummaryCards(double totalGave, double totalGot, double netBalance) {
    String netLabel = 'SETTLED';
    PdfColor netColor = PdfColors.grey800;
    if (netBalance > 0) {
      netLabel = 'YOU WILL GET (Customer Owes)';
      netColor = _gaveRed;
    } else if (netBalance < 0) {
      netLabel = 'YOU WILL GIVE (Shop Owes)';
      netColor = _gotGreen;
    }

    return pw.Row(
      children: [
        pw.Expanded(
          child: pw.Container(
            padding: const pw.EdgeInsets.symmetric(vertical: 8, horizontal: 10),
            decoration: pw.BoxDecoration(
              color: PdfColor.fromHex('#FFEBEE'),
              borderRadius: pw.BorderRadius.circular(4),
              border: pw.Border.all(color: PdfColor.fromHex('#FFCDD2')),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('TOTAL GAVE (DEBIT / 🔴)', style: pw.TextStyle(fontSize: 7, fontWeight: pw.FontWeight.bold, color: _gaveRed)),
                pw.SizedBox(height: 2),
                pw.Text('Rs. ${totalGave.toStringAsFixed(2)}', style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold, color: _gaveRed)),
              ],
            ),
          ),
        ),
        pw.SizedBox(width: 8),
        pw.Expanded(
          child: pw.Container(
            padding: const pw.EdgeInsets.symmetric(vertical: 8, horizontal: 10),
            decoration: pw.BoxDecoration(
              color: PdfColor.fromHex('#E8F5E9'),
              borderRadius: pw.BorderRadius.circular(4),
              border: pw.Border.all(color: PdfColor.fromHex('#C8E6C9')),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('TOTAL GOT (CREDIT / 🟢)', style: pw.TextStyle(fontSize: 7, fontWeight: pw.FontWeight.bold, color: _gotGreen)),
                pw.SizedBox(height: 2),
                pw.Text('Rs. ${totalGot.toStringAsFixed(2)}', style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold, color: _gotGreen)),
              ],
            ),
          ),
        ),
        pw.SizedBox(width: 8),
        pw.Expanded(
          child: pw.Container(
            padding: const pw.EdgeInsets.symmetric(vertical: 8, horizontal: 10),
            decoration: pw.BoxDecoration(
              color: PdfColor.fromHex('#E8EAF6'),
              borderRadius: pw.BorderRadius.circular(4),
              border: pw.Border.all(color: PdfColor.fromHex('#C5CAE9')),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('CLOSING BALANCE ($netLabel)', style: pw.TextStyle(fontSize: 7, fontWeight: pw.FontWeight.bold, color: netColor)),
                pw.SizedBox(height: 2),
                pw.Text('Rs. ${netBalance.abs().toStringAsFixed(2)}', style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold, color: netColor)),
              ],
            ),
          ),
        ),
      ],
    );
  }

  static pw.Widget _buildShopSummaryCards(double receivables, double payables, double overallGave, double overallGot) {
    return pw.Row(
      children: [
        pw.Expanded(
          child: pw.Container(
            padding: const pw.EdgeInsets.all(8),
            decoration: pw.BoxDecoration(
              color: PdfColor.fromHex('#FFEBEE'),
              borderRadius: pw.BorderRadius.circular(4),
              border: pw.Border.all(color: PdfColor.fromHex('#FFCDD2')),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('TOTAL RECEIVABLES (YOU GET)', style: pw.TextStyle(fontSize: 7, fontWeight: pw.FontWeight.bold, color: _gaveRed)),
                pw.SizedBox(height: 2),
                pw.Text('Rs. ${receivables.toStringAsFixed(2)}', style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold, color: _gaveRed)),
              ],
            ),
          ),
        ),
        pw.SizedBox(width: 6),
        pw.Expanded(
          child: pw.Container(
            padding: const pw.EdgeInsets.all(8),
            decoration: pw.BoxDecoration(
              color: PdfColor.fromHex('#E8F5E9'),
              borderRadius: pw.BorderRadius.circular(4),
              border: pw.Border.all(color: PdfColor.fromHex('#C8E6C9')),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('TOTAL PAYABLES (YOU GIVE)', style: pw.TextStyle(fontSize: 7, fontWeight: pw.FontWeight.bold, color: _gotGreen)),
                pw.SizedBox(height: 2),
                pw.Text('Rs. ${payables.toStringAsFixed(2)}', style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold, color: _gotGreen)),
              ],
            ),
          ),
        ),
        pw.SizedBox(width: 6),
        pw.Expanded(
          child: pw.Container(
            padding: const pw.EdgeInsets.all(8),
            decoration: pw.BoxDecoration(
              color: _greyLight,
              borderRadius: pw.BorderRadius.circular(4),
              border: pw.Border.all(color: PdfColors.grey300),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('TOTAL TRANSACTION VOLUME', style: pw.TextStyle(fontSize: 7, fontWeight: pw.FontWeight.bold, color: _greyDark)),
                pw.SizedBox(height: 2),
                pw.Text('Rs. ${(overallGave + overallGot).toStringAsFixed(2)}', style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold)),
              ],
            ),
          ),
        ),
      ],
    );
  }

  static pw.Widget _buildTransactionLedgerTable(List<KhataTransaction> chronoTxs) {
    double runningBalance = 0.0;

    final tableRows = <pw.TableRow>[
      // Table Header
      pw.TableRow(
        decoration: pw.BoxDecoration(color: _brandPrimary),
        children: [
          _buildTableCell('Date', isHeader: true, flex: 2),
          _buildTableCell('Details / Ref', isHeader: true, flex: 3),
          _buildTableCell('Mode', isHeader: true, flex: 2),
          _buildTableCell('You Gave (Dr)', isHeader: true, alignRight: true, flex: 2),
          _buildTableCell('You Got (Cr)', isHeader: true, alignRight: true, flex: 2),
          _buildTableCell('Balance (Rs)', isHeader: true, alignRight: true, flex: 2),
        ],
      ),
    ];

    for (int i = 0; i < chronoTxs.length; i++) {
      final tx = chronoTxs[i];
      if (tx.isGave) {
        runningBalance += tx.amount;
      } else {
        runningBalance -= tx.amount;
      }

      final isEven = i % 2 == 0;
      final rowBg = isEven ? PdfColors.white : _greyLight;

      String details = tx.notes ?? '';
      if (tx.invoiceId != null && tx.invoiceId!.isNotEmpty) {
        details = details.isEmpty ? 'Invoice Ref' : '$details (Inv)';
      }

      String balText = '';
      if (runningBalance > 0) {
        balText = '${runningBalance.toStringAsFixed(0)} Dr';
      } else if (runningBalance < 0) {
        balText = '${runningBalance.abs().toStringAsFixed(0)} Cr';
      } else {
        balText = '0 (Settled)';
      }

      tableRows.add(
        pw.TableRow(
          decoration: pw.BoxDecoration(color: rowBg),
          children: [
            _buildTableCell(DateFormat('dd/MM/yyyy').format(tx.transactionDate), flex: 2),
            _buildTableCell(details.isEmpty ? '-' : details, flex: 3),
            _buildTableCell(tx.paymentMode, flex: 2),
            _buildTableCell(tx.isGave ? 'Rs. ${tx.amount.toStringAsFixed(0)}' : '-', alignRight: true, flex: 2, textColor: tx.isGave ? _gaveRed : null),
            _buildTableCell(tx.isGot ? 'Rs. ${tx.amount.toStringAsFixed(0)}' : '-', alignRight: true, flex: 2, textColor: tx.isGot ? _gotGreen : null),
            _buildTableCell(balText, alignRight: true, flex: 2, isBold: true),
          ],
        ),
      );
    }

    if (chronoTxs.isEmpty) {
      tableRows.add(
        pw.TableRow(
          children: [
            pw.Padding(
              padding: const pw.EdgeInsets.all(12),
              child: pw.Center(
                child: pw.Text('No ledger transactions recorded in this period.', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
              ),
            ),
          ],
        ),
      );
    }

    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
      children: tableRows,
    );
  }

  static pw.Widget _buildCustomerSummariesTable(List<CustomerKhataSummary> customerSummaries) {
    final tableRows = <pw.TableRow>[
      // Table Header
      pw.TableRow(
        decoration: pw.BoxDecoration(color: _brandPrimary),
        children: [
          _buildTableCell('S.No', isHeader: true, flex: 1),
          _buildTableCell('Customer Name', isHeader: true, flex: 4),
          _buildTableCell('Mobile', isHeader: true, flex: 3),
          _buildTableCell('Total Gave (Dr)', isHeader: true, alignRight: true, flex: 3),
          _buildTableCell('Total Got (Cr)', isHeader: true, alignRight: true, flex: 3),
          _buildTableCell('Net Status', isHeader: true, alignRight: true, flex: 3),
        ],
      ),
    ];

    for (int i = 0; i < customerSummaries.length; i++) {
      final s = customerSummaries[i];
      final isEven = i % 2 == 0;
      final rowBg = isEven ? PdfColors.white : _greyLight;

      String netStr = 'Settled';
      PdfColor netCol = PdfColors.grey800;
      if (s.netBalance > 0) {
        netStr = 'Rs. ${s.netBalance.toStringAsFixed(0)} (Get)';
        netCol = _gaveRed;
      } else if (s.netBalance < 0) {
        netStr = 'Rs. ${s.netBalance.abs().toStringAsFixed(0)} (Give)';
        netCol = _gotGreen;
      }

      tableRows.add(
        pw.TableRow(
          decoration: pw.BoxDecoration(color: rowBg),
          children: [
            _buildTableCell('${i + 1}', flex: 1),
            _buildTableCell(s.customer.customerName, flex: 4, isBold: true),
            _buildTableCell(s.customer.mobile ?? '-', flex: 3),
            _buildTableCell('Rs. ${s.totalGave.toStringAsFixed(0)}', alignRight: true, flex: 3, textColor: _gaveRed),
            _buildTableCell('Rs. ${s.totalGot.toStringAsFixed(0)}', alignRight: true, flex: 3, textColor: _gotGreen),
            _buildTableCell(netStr, alignRight: true, flex: 3, isBold: true, textColor: netCol),
          ],
        ),
      );
    }

    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
      children: tableRows,
    );
  }

  static pw.Widget _buildTableCell(
    String text, {
    bool isHeader = false,
    bool alignRight = false,
    bool isBold = false,
    int flex = 1,
    PdfColor? textColor,
  }) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 5),
      child: pw.Text(
        text,
        textAlign: alignRight ? pw.TextAlign.right : pw.TextAlign.left,
        style: pw.TextStyle(
          fontSize: isHeader ? 8 : 8,
          fontWeight: (isHeader || isBold) ? pw.FontWeight.bold : pw.FontWeight.normal,
          color: isHeader ? PdfColors.white : (textColor ?? PdfColors.black),
        ),
      ),
    );
  }

  static pw.Widget _buildSignatureBlock(Profile shop) {
    final shopNameStr = shop.shopName ?? 'My Shop';

    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      crossAxisAlignment: pw.CrossAxisAlignment.end,
      children: [
        pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text('Notes / Disclaimer:', style: pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold, color: _greyDark)),
            pw.Text('This statement is generated automatically by InvoiceHub Khata System.', style: const pw.TextStyle(fontSize: 7, color: PdfColors.grey600)),
            pw.Text('For any discrepancy, please contact $shopNameStr within 7 days.', style: const pw.TextStyle(fontSize: 7, color: PdfColors.grey600)),
          ],
        ),
        pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.center,
          children: [
            pw.Container(
              width: 120,
              height: 1,
              color: PdfColors.grey400,
            ),
            pw.SizedBox(height: 4),
            pw.Text('Authorized Signature', style: pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold)),
            pw.Text('For $shopNameStr', style: const pw.TextStyle(fontSize: 7, color: PdfColors.grey700)),
          ],
        ),
      ],
    );
  }
}
