import 'dart:typed_data';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:invoicehub/models/profile.dart';
import 'package:invoicehub/models/business_models.dart';
import 'package:invoicehub/models/invoice_model.dart';

class PdfService {
  // Match these to AppColors.primary / AppColors.secondary so the PDF
  // looks like the rest of the app.
  static final PdfColor _brandPrimary = PdfColor.fromHex('#3D5AFE');
  static final PdfColor _brandSecondary = PdfColor.fromHex('#00BFA6');
  static final PdfColor _brandPrimaryDark = PdfColor.fromHex('#2A3EB1');

  static Future<Uint8List> generateInvoicePdf({
    required Profile shop,
    required Customer? customer,
    required Invoice invoice,
    required List<InvoiceItem> items,
    Uint8List? signatureBytes,
    PdfPageFormat format = PdfPageFormat.a4,
  }) async {
    final fontBase = await PdfGoogleFonts.notoSansRegular();
    final fontBold = await PdfGoogleFonts.notoSansBold();

    final pdf = pw.Document(
      theme: pw.ThemeData.withFont(
        base: fontBase,
        bold: fontBold,
      ),
    );
    final signatureImage = signatureBytes != null ? pw.MemoryImage(signatureBytes) : null;

    pdf.addPage(
      pw.MultiPage(
        pageFormat: format,
        margin: const pw.EdgeInsets.fromLTRB(28, 24, 28, 24),
        header: (context) => context.pageNumber == 1
            ? pw.SizedBox.shrink()
            : pw.Padding(
                padding: const pw.EdgeInsets.only(bottom: 8),
                child: pw.Text(
                  'Invoice ${invoice.invoiceNumber} (contd.)',
                  style: pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
                ),
              ),
        footer: (context) => pw.Padding(
          padding: const pw.EdgeInsets.only(top: 8),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text('Generated by InvoiceHub', style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
              pw.Text(
                'Page ${context.pageNumber} of ${context.pagesCount}',
                style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
              ),
            ],
          ),
        ),
        build: (pw.Context context) {
          return [
            _buildHeader(shop, invoice),
            pw.SizedBox(height: 16),
            _buildInfoSection(shop, customer, invoice),
            pw.SizedBox(height: 16),
            _buildItemsTable(items),
            pw.Spacer(),
            _buildTotalSection(invoice),
            pw.SizedBox(height: 16),
            _buildTermsAndSignature(shop, customer, signatureImage),
          ];
        },
      ),
    );

    return pdf.save();
  }

  static pw.Widget _buildHeader(Profile shop, Invoice invoice) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.symmetric(horizontal: 20, vertical: 16),
      decoration: pw.BoxDecoration(
        borderRadius: pw.BorderRadius.circular(6),
        gradient: pw.LinearGradient(
          colors: [_brandPrimary, _brandSecondary],
          begin: pw.Alignment.topLeft,
          end: pw.Alignment.bottomRight,
        ),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Center(
            child: pw.Text(
              '|| Jay Swaminarayan ||',
              style: pw.TextStyle(
                fontSize: 10,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.white,
                letterSpacing: 1.2,
              ),
            ),
          ),
          pw.SizedBox(height: 12),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      shop.shopName ?? 'My Shop',
                      style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold, color: PdfColors.white),
                    ),
                    if (shop.address != null)
                      pw.Padding(
                        padding: const pw.EdgeInsets.only(top: 3),
                        child: pw.Text(shop.address!, style: const pw.TextStyle(fontSize: 10, color: PdfColors.white)),
                      ),
                    if (shop.gstNumber != null)
                      pw.Padding(
                        padding: const pw.EdgeInsets.only(top: 5),
                        child: pw.Text(
                          'GSTIN: ${shop.gstNumber}',
                          style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold, color: PdfColors.white),
                        ),
                      ),
                  ],
                ),
              ),
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.end,
                children: [
                  pw.Text(
                    'TAX INVOICE',
                    style: pw.TextStyle(fontSize: 22, color: PdfColors.white, fontWeight: pw.FontWeight.bold),
                  ),
                  pw.SizedBox(height: 8),
                  pw.Text('Invoice No: ${invoice.invoiceNumber}', style: const pw.TextStyle(fontSize: 10, color: PdfColors.white)),
                  pw.Text('Date: ${DateFormat('dd-MM-yyyy').format(invoice.invoiceDate)}', style: const pw.TextStyle(fontSize: 10, color: PdfColors.white)),
                  if (shop.mobile != null) ...[
                    pw.SizedBox(height: 4),
                    pw.Text('Phone: ${shop.mobile}', style: const pw.TextStyle(fontSize: 10, color: PdfColors.white)),
                  ],
                  if (shop.ownerName != null) ...[
                    pw.SizedBox(height: 2),
                    pw.Text(
                      'Owner: ${shop.ownerName}',
                      style: pw.TextStyle(fontSize: 9, fontStyle: pw.FontStyle.italic, color: PdfColors.white),
                    ),
                  ],
                ],
              ),
            ],
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildInfoSection(Profile shop, Customer? customer, Invoice invoice) {
    return pw.Row(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Expanded(
          child: pw.Container(
            decoration: pw.BoxDecoration(border: pw.Border.all(color: PdfColors.grey300), borderRadius: pw.BorderRadius.circular(4)),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Container(
                  padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 5),
                  decoration: pw.BoxDecoration(color: PdfColors.grey200),
                  width: double.infinity,
                  child: pw.Text('Bill To', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
                ),
                pw.Padding(
                  padding: const pw.EdgeInsets.all(8),
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(customer?.customerName ?? 'Walk-in Customer', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 11)),
                      pw.SizedBox(height: 2),
                      pw.Text(customer?.address ?? '', style: const pw.TextStyle(fontSize: 9)),
                      pw.Text('GSTIN: ${customer?.gstNumber ?? 'N/A'}', style: const pw.TextStyle(fontSize: 9)),
                      pw.Text('Phone: ${customer?.mobile ?? ''}', style: const pw.TextStyle(fontSize: 9)),
                    ],
                  ),
                ),
              ],
            ),
          ),
        ),
        pw.SizedBox(width: 16),
        pw.Expanded(
          child: pw.Container(
            decoration: pw.BoxDecoration(border: pw.Border.all(color: PdfColors.grey300), borderRadius: pw.BorderRadius.circular(4)),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Container(
                  padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 5),
                  decoration: pw.BoxDecoration(color: PdfColors.grey200),
                  width: double.infinity,
                  child: pw.Text('Shipping Details', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
                ),
                pw.Padding(
                  padding: const pw.EdgeInsets.all(8),
                  child: pw.Text(customer?.address ?? 'Same as billing', style: const pw.TextStyle(fontSize: 9)),
                ),
              ],
            ),
          ),
        ),
      ],
    );
  }

  static pw.Widget _buildItemsTable(List<InvoiceItem> items) {
    final headers = ['S.No', 'Product Description', 'Qty', 'Rate', 'GST%', 'Total'];

    return pw.TableHelper.fromTextArray(
      headers: headers,
      data: List.generate(items.length, (index) {
        final item = items[index];
        final total = (item.quantity * item.rate) * (1 + (item.gstPercentage / 100));
        return [
          '${index + 1}',
          item.productName ?? 'Product',
          item.quantity % 1 == 0 ? item.quantity.toInt().toString() : item.quantity.toStringAsFixed(2),
          item.rate.toStringAsFixed(2),
          '${item.gstPercentage.toStringAsFixed(0)}%',
          total.toStringAsFixed(2),
        ];
      }),
      headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white, fontSize: 10),
      headerDecoration: pw.BoxDecoration(color: _brandPrimaryDark),
      cellStyle: const pw.TextStyle(fontSize: 10),
      cellHeight: 26,
      border: pw.TableBorder.symmetric(inside: const pw.BorderSide(color: PdfColors.grey300, width: 0.5)),
      cellAlignments: {
        0: pw.Alignment.centerLeft,
        1: pw.Alignment.centerLeft,
        2: pw.Alignment.centerRight,
        3: pw.Alignment.centerRight,
        4: pw.Alignment.centerRight,
        5: pw.Alignment.centerRight,
      },
      columnWidths: {
        0: const pw.FlexColumnWidth(0.6),
        1: const pw.FlexColumnWidth(3),
        2: const pw.FlexColumnWidth(0.8),
        3: const pw.FlexColumnWidth(1),
        4: const pw.FlexColumnWidth(0.8),
        5: const pw.FlexColumnWidth(1.1),
      },
    );
  }

  static pw.Widget _buildTotalSection(Invoice invoice) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.end,
      children: [
        pw.Container(
          width: 220,
          padding: const pw.EdgeInsets.all(10),
          decoration: pw.BoxDecoration(
            color: PdfColors.grey100,
            borderRadius: pw.BorderRadius.circular(4),
          ),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              _buildTotalRow('Subtotal', 'Rs. ${invoice.subtotal.toStringAsFixed(2)}'),
              _buildTotalRow('GST Total', 'Rs. ${invoice.gstTotal.toStringAsFixed(2)}'),
              pw.Divider(color: PdfColors.grey400, height: 10),
              _buildTotalRow('Grand Total', 'Rs. ${invoice.grandTotal.toStringAsFixed(2)}', isBold: true),
            ],
          ),
        ),
      ],
    );
  }

  static pw.Widget _buildTotalRow(String label, String value, {bool isBold = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 2),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            label,
            style: pw.TextStyle(
              fontSize: isBold ? 12 : 10,
              fontWeight: isBold ? pw.FontWeight.bold : null,
              color: isBold ? PdfColors.black : PdfColors.grey700,
            ),
          ),
          pw.Text(
            value,
            style: pw.TextStyle(
              fontSize: isBold ? 14 : 10,
              fontWeight: isBold ? pw.FontWeight.bold : null,
              color: isBold ? _brandPrimaryDark : PdfColors.black,
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildTermsAndSignature(Profile shop, Customer? customer, pw.MemoryImage? signatureImage) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Divider(color: PdfColors.grey300),
        pw.SizedBox(height: 6),
        pw.Row(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Expanded(
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text('Terms & Conditions', style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold)),
                  pw.SizedBox(height: 3),
                  pw.Text('1. Goods once sold will not be taken back.', style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700)),
                  pw.Text('2. Subject to ${shop.city ?? 'Local'} Jurisdiction.', style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700)),
                  pw.SizedBox(height: 24),
                  pw.Text('Customer Signature', style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600)),
                  pw.SizedBox(height: 24),
                  pw.Container(width: 120, height: 0.5, color: PdfColors.grey500),
                ],
              ),
            ),
            pw.SizedBox(width: 24),
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Text('For ${shop.shopName ?? 'My Shop'}', style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600)),
                pw.SizedBox(height: 6),
                if (signatureImage != null)
                  pw.Image(signatureImage, height: 40, fit: pw.BoxFit.contain)
                else
                  pw.SizedBox(height: 40),
                pw.Container(width: 130, height: 0.5, color: PdfColors.grey500),
                pw.SizedBox(height: 3),
                pw.Text('Authorised Signatory', style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
              ],
            ),
          ],
        ),
      ],
    );
  }
}
