import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import 'package:invoicehub/models/business_models.dart';
import 'package:invoicehub/models/khata_model.dart';
import 'package:invoicehub/models/invoice_model.dart';
import 'package:invoicehub/providers/auth_provider.dart';
import 'package:invoicehub/providers/customer_provider.dart';
import 'package:invoicehub/providers/invoice_provider.dart';
import 'package:invoicehub/providers/khata_provider.dart';
import 'package:invoicehub/widgets/app_colors.dart';

class AddKhataEntryDialog extends ConsumerStatefulWidget {
  final Customer? initialCustomer;
  final String initialType; // 'GAVE' or 'GOT'

  const AddKhataEntryDialog({
    super.key,
    this.initialCustomer,
    this.initialType = 'GAVE',
  });

  static Future<void> show(
    BuildContext context, {
    Customer? customer,
    String type = 'GAVE',
  }) {
    return showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (ctx) => AddKhataEntryDialog(
        initialCustomer: customer,
        initialType: type,
      ),
    );
  }

  @override
  ConsumerState<AddKhataEntryDialog> createState() => _AddKhataEntryDialogState();
}

class _AddKhataEntryDialogState extends ConsumerState<AddKhataEntryDialog> {
  final _formKey = GlobalKey<FormState>();
  late String _type; // 'GAVE' or 'GOT'
  Customer? _selectedCustomer;
  Invoice? _selectedInvoice;
  String? _selectedInvoiceId;
  bool _isCustomInvoice = false;

  final TextEditingController _amountController = TextEditingController();
  final TextEditingController _notesController = TextEditingController();
  final TextEditingController _refNoController = TextEditingController();
  String _paymentMode = 'CASH';
  DateTime _selectedDate = DateTime.now();
  bool _isSaving = false;

  final List<String> _paymentModes = [
    'CASH',
    'UPI',
    'BANK_TRANSFER',
    'CHEQUE',
    'INVOICE',
  ];

  @override
  void initState() {
    super.initState();
    _type = widget.initialType;
    _selectedCustomer = widget.initialCustomer;
  }

  @override
  void dispose() {
    _amountController.dispose();
    _notesController.dispose();
    _refNoController.dispose();
    super.dispose();
  }

  Future<void> _pickDate() async {
    final picked = await showDatePicker(
      context: context,
      initialDate: _selectedDate,
      firstDate: DateTime(2020),
      lastDate: DateTime(2100),
    );
    if (picked != null) {
      final timePicked = await showTimePicker(
        context: context,
        initialTime: TimeOfDay.fromDateTime(_selectedDate),
      );
      setState(() {
        _selectedDate = DateTime(
          picked.year,
          picked.month,
          picked.day,
          timePicked?.hour ?? _selectedDate.hour,
          timePicked?.minute ?? _selectedDate.minute,
        );
      });
    }
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;
    if (_selectedCustomer == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please select a customer')),
      );
      return;
    }

    final profile = ref.read(profileProvider).value;
    if (profile == null) return;

    setState(() => _isSaving = true);

    try {
      final amount = double.tryParse(_amountController.text.trim()) ?? 0.0;
      final refNo = _refNoController.text.trim().isEmpty ? null : _refNoController.text.trim();
      final newTx = KhataTransaction(
        id: '', // Generated by Supabase
        shopId: profile.id,
        customerId: _selectedCustomer!.id,
        invoiceId: _selectedInvoiceId,
        transactionType: _type,
        amount: amount,
        paymentMode: _paymentMode,
        transactionDate: _selectedDate,
        notes: _notesController.text.trim().isEmpty
            ? null
            : _notesController.text.trim(),
        referenceNo: refNo,
        createdAt: DateTime.now(),
      );

      await ref.read(khataControllerProvider).addTransaction(newTx);

      if (mounted) {
        Navigator.pop(context);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              _type == 'GAVE'
                  ? 'Udhar of ₹${amount.toStringAsFixed(0)} added for ${_selectedCustomer!.customerName}'
                  : 'Payment of ₹${amount.toStringAsFixed(0)} received from ${_selectedCustomer!.customerName}',
            ),
            backgroundColor: _type == 'GAVE' ? AppColors.khataGave : AppColors.khataGot,
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error saving entry: $e'), backgroundColor: Colors.red),
        );
      }
    } finally {
      if (mounted) setState(() => _isSaving = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final customersAsync = ref.watch(customersProvider);
    final isGave = _type == 'GAVE';
    final accentColor = isGave ? AppColors.khataGave : AppColors.khataGot;

    return Container(
      decoration: const BoxDecoration(
        color: AppColors.surface,
        borderRadius: BorderRadius.vertical(top: Radius.circular(28)),
      ),
      padding: EdgeInsets.only(
        top: 24,
        left: 20,
        right: 20,
        bottom: MediaQuery.of(context).viewInsets.bottom + 24,
      ),
      child: SingleChildScrollView(
        child: Form(
          key: _formKey,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              // Modal Handle Indicator
              Center(
                child: Container(
                  width: 40,
                  height: 4,
                  decoration: BoxDecoration(
                    color: Colors.grey.shade300,
                    borderRadius: BorderRadius.circular(2),
                  ),
                ),
              ),
              const SizedBox(height: 16),

              // Title
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(
                    isGave ? 'You Gave (Aapne Diya)' : 'You Got (Aapko Mila)',
                    style: TextStyle(
                      fontSize: 20,
                      fontWeight: FontWeight.bold,
                      color: accentColor,
                    ),
                  ),
                  IconButton(
                    icon: const Icon(Icons.close),
                    onPressed: () => Navigator.pop(context),
                  ),
                ],
              ),
              const SizedBox(height: 12),

              // Toggle Type Selector (GAVE / GOT)
              Container(
                decoration: BoxDecoration(
                  color: AppColors.background,
                  borderRadius: BorderRadius.circular(16),
                  border: Border.all(color: AppColors.border),
                ),
                child: Row(
                  children: [
                    Expanded(
                      child: GestureDetector(
                        onTap: () => setState(() => _type = 'GAVE'),
                        child: AnimatedContainer(
                          duration: const Duration(milliseconds: 200),
                          padding: const EdgeInsets.symmetric(vertical: 12),
                          decoration: BoxDecoration(
                            color: isGave ? AppColors.khataGave : Colors.transparent,
                            borderRadius: BorderRadius.circular(15),
                          ),
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              Icon(
                                Icons.arrow_upward_rounded,
                                color: isGave ? Colors.white : AppColors.khataGave,
                                size: 18,
                              ),
                              const SizedBox(width: 6),
                              Text(
                                'YOU GAVE (Udhar)',
                                style: TextStyle(
                                  fontWeight: FontWeight.bold,
                                  color: isGave ? Colors.white : AppColors.khataGave,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ),
                    Expanded(
                      child: GestureDetector(
                        onTap: () => setState(() => _type = 'GOT'),
                        child: AnimatedContainer(
                          duration: const Duration(milliseconds: 200),
                          padding: const EdgeInsets.symmetric(vertical: 12),
                          decoration: BoxDecoration(
                            color: !isGave ? AppColors.khataGot : Colors.transparent,
                            borderRadius: BorderRadius.circular(15),
                          ),
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              Icon(
                                Icons.arrow_downward_rounded,
                                color: !isGave ? Colors.white : AppColors.khataGot,
                                size: 18,
                              ),
                              const SizedBox(width: 6),
                              Text(
                                'YOU GOT (Payment)',
                                style: TextStyle(
                                  fontWeight: FontWeight.bold,
                                  color: !isGave ? Colors.white : AppColors.khataGot,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 20),

              // Customer Dropdown / Selector if not pre-selected
              if (widget.initialCustomer == null)
                customersAsync.when(
                  data: (customers) => DropdownButtonFormField<Customer>(
                    value: _selectedCustomer,
                    decoration: InputDecoration(
                      labelText: 'Select Customer',
                      prefixIcon: const Icon(Icons.person_outline),
                      border: OutlineInputBorder(borderRadius: BorderRadius.circular(16)),
                    ),
                    items: customers.map((c) {
                      return DropdownMenuItem<Customer>(
                        value: c,
                        child: Text('${c.customerName} ${c.mobile != null ? "(${c.mobile})" : ""}'),
                      );
                    }).toList(),
                    onChanged: (val) => setState(() => _selectedCustomer = val),
                    validator: (val) => val == null ? 'Customer is required' : null,
                  ),
                  loading: () => const LinearProgressIndicator(),
                  error: (_, __) => const SizedBox.shrink(),
                )
              else
                Container(
                  padding: const EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    color: AppColors.background,
                    borderRadius: BorderRadius.circular(14),
                    border: Border.all(color: AppColors.border),
                  ),
                  child: Row(
                    children: [
                      CircleAvatar(
                        backgroundColor: accentColor.withOpacity(0.15),
                        child: Text(
                          widget.initialCustomer!.customerName[0].toUpperCase(),
                          style: TextStyle(fontWeight: FontWeight.bold, color: accentColor),
                        ),
                      ),
                      const SizedBox(width: 12),
                      Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            widget.initialCustomer!.customerName,
                            style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
                          ),
                          if (widget.initialCustomer!.mobile != null)
                            Text(
                              widget.initialCustomer!.mobile!,
                              style: const TextStyle(fontSize: 13, color: AppColors.textSecondary),
                            ),
                        ],
                      ),
                    ],
                  ),
                ),
              const SizedBox(height: 16),

              // Amount Field
              TextFormField(
                controller: _amountController,
                keyboardType: const TextInputType.numberWithOptions(decimal: true),
                autofocus: true,
                style: TextStyle(
                  fontSize: 26,
                  fontWeight: FontWeight.bold,
                  color: accentColor,
                ),
                decoration: InputDecoration(
                  labelText: 'Amount (₹)',
                  prefixIcon: Icon(Icons.currency_rupee, color: accentColor, size: 28),
                  hintText: '0.00',
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(16)),
                  focusedBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(16),
                    borderSide: BorderSide(color: accentColor, width: 2),
                  ),
                ),
                validator: (val) {
                  if (val == null || val.trim().isEmpty) return 'Enter amount';
                  final d = double.tryParse(val.trim());
                  if (d == null || d <= 0) return 'Enter a valid amount';
                  return null;
                },
              ),
              const SizedBox(height: 16),

              // Payment Mode & Date Row
              Row(
                children: [
                  Expanded(
                    child: DropdownButtonFormField<String>(
                      value: _paymentMode,
                      decoration: InputDecoration(
                        labelText: 'Payment Mode',
                        border: OutlineInputBorder(borderRadius: BorderRadius.circular(14)),
                        contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
                      ),
                      items: _paymentModes.map((mode) {
                        return DropdownMenuItem<String>(
                          value: mode,
                          child: Text(mode.replaceAll('_', ' ')),
                        );
                      }).toList(),
                      onChanged: (val) {
                        if (val != null) setState(() => _paymentMode = val);
                      },
                    ),
                  ),
                  const SizedBox(width: 12),
                  InkWell(
                    onTap: _pickDate,
                    borderRadius: BorderRadius.circular(14),
                    child: Container(
                      padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 14),
                      decoration: BoxDecoration(
                        border: Border.all(color: AppColors.border),
                        borderRadius: BorderRadius.circular(14),
                      ),
                      child: Row(
                        children: [
                          const Icon(Icons.calendar_today_rounded, size: 18, color: AppColors.primary),
                          const SizedBox(width: 8),
                          Text(
                            DateFormat('dd MMM').format(_selectedDate),
                            style: const TextStyle(fontWeight: FontWeight.bold),
                          ),
                        ],
                      ),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 16),

              // Dynamic Reference Field based on Payment Mode
              if (_paymentMode == 'UPI') ...[
                const SizedBox(height: 16),
                TextFormField(
                  controller: _refNoController,
                  decoration: InputDecoration(
                    labelText: 'UPI Transaction Ref ID (Optional)',
                    hintText: 'e.g. 123456789012 or UPI Ref No',
                    prefixIcon: const Icon(Icons.qr_code_rounded, color: AppColors.primary),
                    border: OutlineInputBorder(borderRadius: BorderRadius.circular(16)),
                  ),
                ),
              ] else if (_paymentMode == 'INVOICE') ...[
                _buildInvoiceSelectorWidget(context, ref),
              ] else if (_paymentMode == 'CHEQUE' || _paymentMode == 'BANK_TRANSFER') ...[
                const SizedBox(height: 16),
                TextFormField(
                  controller: _refNoController,
                  decoration: InputDecoration(
                    labelText: 'Cheque / Bank Ref No. (Optional)',
                    hintText: 'e.g. Cheque #452109 or NEFT Ref',
                    prefixIcon: const Icon(Icons.account_balance_outlined, color: AppColors.primary),
                    border: OutlineInputBorder(borderRadius: BorderRadius.circular(16)),
                  ),
                ),
              ],
              const SizedBox(height: 16),

              // Notes Field
              TextFormField(
                controller: _notesController,
                decoration: InputDecoration(
                  labelText: 'Notes / Description (Optional)',
                  hintText: 'e.g. Bill payment, Cash given, Notes...',
                  prefixIcon: const Icon(Icons.note_alt_outlined),
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(16)),
                ),
              ),
              const SizedBox(height: 24),

              // Submit Button
              ElevatedButton(
                onPressed: _isSaving ? null : _submit,
                style: ElevatedButton.styleFrom(
                  backgroundColor: accentColor,
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(vertical: 16),
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                  elevation: 2,
                ),
                child: _isSaving
                    ? const SizedBox(
                        height: 22,
                        width: 22,
                        child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2.5),
                      )
                    : Text(
                        _type == 'GAVE' ? 'SAVE (YOU GAVE ₹)' : 'SAVE (YOU GOT ₹)',
                        style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
                      ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildInvoiceSelectorWidget(BuildContext context, WidgetRef ref) {
    final invoicesAsync = ref.watch(invoicesProvider);

    return invoicesAsync.when(
      data: (allInvoices) {
        final customerInvoices = _selectedCustomer == null
            ? <Invoice>[]
            : allInvoices.where((i) => i.customerId == _selectedCustomer!.id).toList();

        return Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const SizedBox(height: 16),
            const Text(
              'Select Customer Invoice',
              style: TextStyle(fontSize: 13, fontWeight: FontWeight.bold, color: AppColors.textSecondary),
            ),
            const SizedBox(height: 6),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 12),
              decoration: BoxDecoration(
                color: AppColors.background,
                borderRadius: BorderRadius.circular(16),
                border: Border.all(color: AppColors.border),
              ),
              child: DropdownButtonHideUnderline(
                child: DropdownButton<String>(
                  value: _isCustomInvoice ? 'CUSTOM' : _selectedInvoiceId,
                  isExpanded: true,
                  hint: Text(
                    customerInvoices.isEmpty
                        ? '+ Enter Custom / Manual Invoice'
                        : 'Choose from ${customerInvoices.length} past invoices...',
                    style: const TextStyle(fontSize: 14, color: AppColors.textSecondary),
                  ),
                  items: [
                    const DropdownMenuItem<String>(
                      value: 'CUSTOM',
                      child: Row(
                        children: [
                          Icon(Icons.edit_note_rounded, size: 20, color: AppColors.primary),
                          SizedBox(width: 8),
                          Text(
                            '+ Enter Custom / Manual Invoice',
                            style: TextStyle(fontWeight: FontWeight.bold, color: AppColors.primary, fontSize: 13),
                          ),
                        ],
                      ),
                    ),
                    ...customerInvoices.map((inv) {
                      final dateStr = DateFormat('dd MMM').format(inv.invoiceDate);
                      return DropdownMenuItem<String>(
                        value: inv.id,
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            Row(
                              children: [
                                const Icon(Icons.receipt_long_rounded, size: 18, color: AppColors.textSecondary),
                                const SizedBox(width: 8),
                                Text(
                                  inv.invoiceNumber,
                                  style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 13),
                                ),
                              ],
                            ),
                            Text(
                              '₹${inv.grandTotal.toStringAsFixed(0)} ($dateStr)',
                              style: const TextStyle(fontWeight: FontWeight.w600, color: AppColors.khataGave, fontSize: 12),
                            ),
                          ],
                        ),
                      );
                    }),
                  ],
                  onChanged: (val) {
                    setState(() {
                      if (val == 'CUSTOM' || val == null) {
                        _isCustomInvoice = true;
                        _selectedInvoice = null;
                        _selectedInvoiceId = null;
                        _refNoController.clear();
                      } else {
                        _isCustomInvoice = false;
                        final inv = customerInvoices.firstWhere((i) => i.id == val);
                        _selectedInvoice = inv;
                        _selectedInvoiceId = inv.id;
                        _refNoController.text = inv.invoiceNumber;
                        _amountController.text = inv.grandTotal.toStringAsFixed(0);
                        _notesController.text = 'Linked to Invoice #${inv.invoiceNumber}';
                      }
                    });
                  },
                ),
              ),
            ),
            if (_selectedInvoice != null && !_isCustomInvoice) ...[
              const SizedBox(height: 8),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                decoration: BoxDecoration(
                  color: AppColors.success.withOpacity(0.1),
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(color: AppColors.success.withOpacity(0.3)),
                ),
                child: Row(
                  children: [
                    const Icon(Icons.check_circle_rounded, color: AppColors.success, size: 18),
                    const SizedBox(width: 8),
                    Expanded(
                      child: Text(
                        'Linked to #${_selectedInvoice!.invoiceNumber} (₹${_selectedInvoice!.grandTotal.toStringAsFixed(0)})',
                        style: const TextStyle(fontSize: 12, fontWeight: FontWeight.bold, color: AppColors.success),
                      ),
                    ),
                  ],
                ),
              ),
            ],
            if (_isCustomInvoice || customerInvoices.isEmpty) ...[
              const SizedBox(height: 12),
              TextFormField(
                controller: _refNoController,
                decoration: InputDecoration(
                  labelText: 'Invoice Number (Manual)',
                  hintText: 'e.g. INV-20260730-001 or Paper Bill #',
                  prefixIcon: const Icon(Icons.receipt_long_rounded, color: AppColors.primary),
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(16)),
                ),
              ),
            ],
          ],
        );
      },
      loading: () => const LinearProgressIndicator(),
      error: (_, __) => const SizedBox.shrink(),
    );
  }
}
